variables:
  ${{ if eq( variables['Build.BuildId'], 0 ) }}:
    command: 'apply'
    arguments: '-f manifest.yaml'
  ${{ else }}:
    command: 'set'  # 'rollout' is not yet available as a kubectl command option 
    arguments: 'image deployment hello-world=$(imgBaseName)/hello:$(Build.BuildId) --all'

trigger:
- main

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Configuration
    jobs:
    - job: Configuration
      displayName: Installing Docker, kubectl, JFrog CLI
      steps:
      - task: DockerInstaller@0
        displayName: Installing Docker
        inputs:
          dockerVersion: '18.09.4'
          
      - task: KubectlInstaller@0
        displayName: Installing kubectl 
        inputs:
          kubectlVersion: 'latest'
        
  - stage: Build
    displayName: 'Building and pushing images'
    jobs:
      - job: Build
        steps:
        - task: Docker@2
          displayName: 'Logging to JFA (Docker task)'
          inputs:
            containerRegistry: 'tf-ado-artifactory-repo-connection'
            command: 'login'
        
        - task: Docker@2
          displayName: 'Building image'
          inputs:
            containerRegistry: 'tf-ado-artifactory-repo-connection'
            repository: 'tf-ado-docker-local/hello'
            command: 'build'
            Dockerfile: '**/Dockerfile'

        - task: ArtifactoryDocker@1
          displayName: 'Pushing image (JFA)'
          inputs:
            command: 'push'
            artifactoryService: 'tf-ado-artifactory-cli-conn'
            targetRepo: 'tf-ado-docker-local/hello'
            imageName: '$(imgBaseName)/hello:$(Build.BuildId)'

  - stage: Deploy
    dependsOn: Build
    displayName: 'Updating cluster resources'
    jobs:
    - job: Deploy
      steps:
      # Deploys containers
      - task: Kubernetes@1
        displayName: 'Pulling image to AKS'
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'tf-ado-aks-connection'
          command: 'apply' #'$(command)'
          arguments: '-f manifest.yaml' #'$(arguments)'
          ${{ if eq( variables['Build.BuildId'], 0 ) }}:
            secretType: 'dockerRegistry'
            containerRegistryType: 'Container Registry'
            dockerRegistryEndpoint: 'tf-ado-artifactory-repo-connection'
            secretName: 'repo-secret'
