variables:
  ${{ if eq( variables['Build.BuildId'], 0 ) }}:
    command: 'apply'
    arguments: '-f path/to/manifests'
  ${{ else }}:
    command: 'set'  # 'rollout' is not yet available as a kubectl command option 
    arguments: 'image [TYPES] hello=hello:$(Build.BuildId) --all'
  imgBaseName: 'tf-ado-imgrepo.westeurope.cloudapp.azure.com/artifactory'
  usingJF: 'false'

trigger:
- main

pool: 
  vmImage: ubuntu-latest

stages:
  - stage: Configuration
    jobs:
    - job: Configuration
      displayName: Installing Docker, kubectl, JFrog CLI
      steps:
      - task: DockerInstaller@0
        displayName: Installing Docker
        inputs:
          dockerVersion: '18.09.4'
          
      - task: KubectlInstaller@0
        displayName: Installing kubectl 
        inputs:
          kubectlVersion: 'latest'

      #- task: ArtifactoryToolsInstaller@1
      #  inputs:
      #    artifactoryService: 'tf-ado-artifactory-cli-conn'
      #    cliInstallationRepo: 'cli'
        
  - stage: Build
    displayName: 'Building and pushing images'
    jobs:
      - job: Build
        steps:
        - task: Docker@2
          condition: ne(variables.usingJF, 'true')
          inputs:
            containerRegistry: 'tf-ado-artifactory-repo-connection'
            command: 'login'
        - task: Docker@2
          inputs:
            containerRegistry: 'tf-ado-artifactory-repo-connection'
            repository: 'artifactory/tf-ado-cicd-repo'
            command: 'build'
            Dockerfile: '**/Dockerfile'
        
        - task: Docker@2
          condition: ne(variables.usingJF, 'true')
          inputs:
            containerRegistry: 'tf-ado-artifactory-repo-connection'
            repository: 'artifactory/tf-ado-cicd-repo'
            command: 'push'
            Dockerfile: '**/Dockerfile'
            
        - task: ArtifactoryDocker@1
          condition: eq(variables.usingJF, 'true')
          inputs:
            command: 'push'
            artifactoryService: 'tf-ado-artifactory-cli-conn'
            targetRepo: 'tf-ado-cicd-repo'
            imageName: '$(imgBaseName)/tf-ado-cicd-repo:$(Build.BuildId)'

  - stage: Deploy
    dependsOn: Build
    displayName: 'Updating cluster resources'
    jobs:
    - job: Deploy
      steps:
      # Deploys containers
      - task: Kubernetes@1
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'tf-ado-aks-connection'
          command: '$(command)'
          arguments: '$(arguments)'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Container Registry'
          dockerRegistryEndpoint: 'tf-ado-artifactory-repo-connection'
