apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-pod
        image: tf-ado-docker-local/hello:latest
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Ingress
metadata:
  name: hello-world-ingress
spec:
  ingressClassName: hello-world-ingress
  rules:
  - http:
    paths:
    - path: /hello-world
      pathPrefix: Prefix
      backend:
        service:
          name: hello-world-service
          port:
            number: 80